name: build-console.yml
on:
  workflow_call:
    inputs:
      dotnet-version:
        description: 'Dotnet Version'
        required: true
        type: string

env:
  PROJECT_PATH: './HardLinkTool.ConsoleApp'

jobs:
  build-console:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'windows-latest','Ubuntu-latest' ]
        Architecture: [ 'x64' ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        name: Setup dotnet
        with:
          dotnet-version: ${{inputs.dotnet-version}}

      - name: Install latest clang and lld
        if: ${{ runner.os != 'Windows' }}
        run: |
          sudo apt-get update

      - name: Build
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            dotnet \
            publish ${{env.PROJECT_PATH}} \
            -c windows-release \
            -a ${{matrix.Architecture}} \
            -o publish \
            //p:ProjectPublishAot=true
          else
            dotnet \
            publish ${{env.PROJECT_PATH}} \
            -c linux-release \
            -a ${{matrix.Architecture}} \
            -o publish \
            /p:ProjectPublishAot=true
          fi
        shell: bash

      - name: Change File Name
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            mv "./publish/HardLinkTool.ConsoleApp.exe" "./publish/HardLinkTool.ConsoleApp-${{runner.os}}-${{matrix.Architecture}}.exe"
          else
            mv "./publish/HardLinkTool.ConsoleApp" "./publish/HardLinkTool.ConsoleApp-${{runner.os}}-${{matrix.Architecture}}"
          fi
        shell: bash

      - name: Remove PDB
        if: ${{ runner.os == 'Windows' }}
        run: |
          rm -Force ./publish/*.pdb

      - name: Remove DBG
        if: ${{ runner.os != 'Windows' }}
        run: |
          rm -f ./publish/*.dbg
          rm -f ./publish/*.pdb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-Console-${{ matrix.Architecture }}
          path: ${{ github.workspace }}/publish/*
