name: Build and Release

on:
  push:
    tags:
      - "v*"

env:
  DOTNET_VERSION: '10.*.*'
  PROJECT_PATH: './HardLinkTool'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'windows-latest','Ubuntu-latest' ]
        Architecture: [ 'x64' ]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        name: Setup dotnet
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      - name: Build
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            dotnet \
            publish ${{env.PROJECT_PATH}} \
            -c windows-release \
            -a ${{matrix.Architecture}} \
            -o publish
          else
            dotnet \
            publish ${{env.PROJECT_PATH}} \
            -c linux-release \
            -a ${{matrix.Architecture}} \
            -o publish
          fi
        shell: bash

      - name: Change File Name
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            mv "./publish/HardLinkTool.exe" "./publish/HardLinkTool-${{runner.os}}-${{matrix.Architecture}}.exe"
          else
            mv "./publish/HardLinkTool" "./publish/HardLinkTool-${{runner.os}}-${{matrix.Architecture}}"
          fi
        shell: bash

      - name: Remove PDB
        if: ${{ runner.os == 'Windows' }}
        run: |
          rm -Force ./publish/*.pdb

      - name: Remove DBG
        if: ${{ runner.os != 'Windows' }}
        run: |
          rm -f ./publish/*.dbg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ matrix.Architecture }}
          path: ${{ github.workspace }}/publish/*
  
  create-release:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloads

      - name: Show artifacts
        run: |
          ls -l downloads

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          generate_release_notes: true
          draft: true
          files: |
            ./downloads/**/*
            LICENSE