name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows-64:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        name: Setup dotnet
        with:
          dotnet-version: '10.*.*'

      - name: Build Windows x64
        run: |
          cd HardLinkTool &&
          dotnet publish -c windows-release -a x64 -f net10.0 -o publish &&
          mv publish/HardLinkTool.exe publish/HardLinkTool-windows-x64.exe.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64
          path: publish/HardLinkTool-windows-x64.exe
  
  build-linux-64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        name: Setup dotnet
        with:
          dotnet-version: '10.*.*'

      - name: Build Linux x64
        run: |
          cd HardLinkTool &&
          dotnet publish -c linux-release -a x64 -f net10.0 -o publish &&
          mv publish/HardLinkTool.exe publish/HardLinkTool-linux-x64.exe.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: publish/HardLinkTool-linux-x64.exe
  
  create-release:
    needs: [ build-windows-64, build-linux-64 ]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloads
          name: windows-x64, linux-x64

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          generate_release_notes: true
          files: |
            downloads/HardLinkTool-windows-x64.exe
            downloads/HardLinkTool-linux-x64.exe
            LICENSE
