name: Build and Release

on:
  push:
    tags:
      - "v*"

env:
  DOTNET_VERSION: '10.0.*'

jobs:
  build-ui:
    uses: ./.github/workflows/build-ui.yml
    with:
      dotnet-version: 10.0.*

  build-console:
    uses: ./.github/workflows/build-console.yml
    with:
      dotnet-version: 10.0.*

  create-release:
    needs: [ build-console, build-ui ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloads

      - name: Show artifacts
        run: |
          ls -l downloads

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          generate_release_notes: true
          draft: true
          files: |
            ./downloads/**/*
            LICENSE
